### ISSUE TITLE
Error: The selector 'demo-app' did not match any elements

### ISSUE THREAD

**Issue by jalexandar** [kdechant/angular5-httpclient-demo#5]
Today, I downloaded a copy of the project and ran into this issue ("Error: The selector 'demo-app' did not match any elements) while executing the project. I found `<demo-app></demo-app>` tag is missing in the index.html file. Once added, the application started to work.

**Comment by kdechant** [comment]
The selector is in index.html here: https://github.com/kdechant/angular5-httpclient-demo/blob/9f46ba5e28d09b2a96dd25e17b5a62aab986b7a9/index.html#L11

If you're looking at the file /src/index.html, that file is unused by the project. It just needs to be there for webpack to build correctly. The Node server ignores it entirely.

FYI, this project has to use the `npm install` and `npm start` commands exactly as shown in the README. Trying to use any other build commands like `ng serve` won't work because it won't start the Node API server.
